# Shougo_plugins---{{{
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
depends = ['context_filetype.vim']
hook_source = '''
call deoplete#enable()
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/context_filetype.vim'

#---}}}

[[plugins]]
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
depends = ['deoplete.nvim']
build = 'bash install.sh'
#hook---{{{
hook_add = '''
set hidden
let g:LanguageClient_serverCommands = {
      \ 'cpp': ['clangd'],
      \ }
let g:LanguageClient_loadSettings = 1

nnoremap K :call LanguageClient#textDocument_hover()<CR>
nnoremap F :call LanguageClient#textDocument_formatting()<CR>
'''
hook_source = '''
set completefunc=LanguageClient#complete
'''
#---}}}

[[plugins]]
repo = 'simeji/winresizer'
# hook_add {{{
hook_add = '''
let g:winresizer_start_key = '<C-T>'
'''
# }}}

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'osyo-manga/vim-over'
# hook_add {{{
hook_add = '''
" over.vimの起動
nnoremap <silent> <Leader>m :OverCommandLine<CR>

" カーソル下の単語をハイライト付きで置換
nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>

"コピーした文字列をハイライト付きで置換
nnoremap subp y:OverCommandLine<CR>%s!<C-r>=substitute(@0, '!', '\\!', 'g')<CR>!!gI<Left><Left><Left>
'''
#}}}

#カッコ補完
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'mattn/sonictemplate-vim'
# on_i = 1
#sonictemplate---{{{
hook_add = '''
let g:sonictemplate_vim_template_dir = [
    \'~/.config/nvim/template'
    \]

'''

#}}}

#airline---{{{
[[plugins]]
repo = 'vim-airline/vim-airline'
#hook_add ---{{{
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline_solarized_bg='bubblegum'
set laststatus=2
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#wordcount#enabled = 1
let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'y', 'z']]
let g:airline_section_c = '%t'
let g:airline_section_x = '%{&filetype}'
let g:airline_section_z = '%3l:%2v %{airline#extensions#ale#get_warning()} %{airline#extensions#ale#get_error()}'
let g:airline#extensions#ale#error_symbol = ' '
let g:airline#extensions#ale#warning_symbol = ' '
let g:airline#extensions#default#section_truncate_width = {}
let g:airline#extensions#whitespace#enabled = 1
'''
#}}}

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'tpope/vim-fugitive'
#---}}}

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'vim-scripts/fcitx.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'
