[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'simeji/winresizer'
# hook_add {{{
hook_add = '''
let g:winresizer_start_key = '<C-S>'
'''
# }}}

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'osyo-manga/vim-over'
# hook_add {{{
hook_add = '''
" over.vimの起動
nnoremap <silent> <Leader>m :OverCommandLine<CR>

" カーソル下の単語をハイライト付きで置換
nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>

"コピーした文字列をハイライト付きで置換
nnoremap subp y:OverCommandLine<CR>%s!<C-r>=substitute(@0, '!', '\\!', 'g')<CR>!!gI<Left><Left><Left>
'''
#}}}


#カッコ補完
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

#deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
# hook_add {{{
hook_add = '''
    source ~/.config/nvim/toml/deoplete.rc.vim
    "let g:deoplete#enable_at_startup = 1
    "let g:deoplete#enable_at_smartcase = 1
    "let g:deoplete#enable_camel_case = 1
    " let g:deoplete#auto_complete_delay = 1
    "let g:deoplete#auto_complete_start_length = 1
'''
# }}}

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_i = 1
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'itchyny/lightline.vim'


[[plugins]]
repo = 'mattn/sonictemplate-vim'
# on_i = 1
#sonictemplate---{{{
hook_add = '''
let g:sonictemplate_vim_template_dir = [
    \'~/.config/nvim/template'
    \]

'''

#}}}

[[plugins]]
repo = 'w0rp/ale'
# hook_add---{{{
hook_add = '''
" エラー行に表示するマーク
let g:ale_sign_error = '☒'
let g:ale_sign_warning = '⚠'
" エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
" エラー表示の列を常時表示
let g:ale_sign_column_always = 1

" エラー行にジャンプ
nmap <silent> [ale]<C-P> <Plug>(ale_previous)
nmap <silent> [ale]<C-N> <Plug>(ale_next)'''
# }}}

[[plugins]]
repo = 'vim-scripts/javacomplete'
#hook_add {{{
hook_add = '''
  autocmd FileType java :setlocal omnifunc=javacomplete#Complete
  autocmd FileType java :setlocal completefunc=javacomplete#CompleteParamsInfo
'''
#}}}
