# Shougo_plugins---{{{
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
# hook_add {{{
hook_add = '''
    source ~/.config/nvim/toml/deoplete.rc.vim
    "let g:deoplete#enable_at_startup = 1
    "let g:deoplete#enable_at_smartcase = 1
    "let g:deoplete#enable_camel_case = 1
    " let g:deoplete#auto_complete_delay = 1
    "let g:deoplete#auto_complete_start_length = 1
'''
# }}}

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_i = 1
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1
#---}}}

[[plugins]]
repo = 'simeji/winresizer'
# hook_add {{{
hook_add = '''
let g:winresizer_start_key = '<C-S>'
'''
# }}}

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'osyo-manga/vim-over'
# hook_add {{{
hook_add = '''
" over.vimの起動
nnoremap <silent> <Leader>m :OverCommandLine<CR>

" カーソル下の単語をハイライト付きで置換
nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>

"コピーした文字列をハイライト付きで置換
nnoremap subp y:OverCommandLine<CR>%s!<C-r>=substitute(@0, '!', '\\!', 'g')<CR>!!gI<Left><Left><Left>
'''
#}}}


#カッコ補完
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'mattn/sonictemplate-vim'
# on_i = 1
#sonictemplate---{{{
hook_add = '''
let g:sonictemplate_vim_template_dir = [
    \'~/.config/nvim/template'
    \]

'''

#}}}

[[plugins]]
repo = 'w0rp/ale'
# hook_add---{{{
hook_add = '''
" エラー行に表示するマーク
let g:ale_sign_error = ''
let g:ale_sign_warning = ''
" エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
" エラー表示の列を常時表示
let g:ale_sign_column_always = 1

" エラー行にジャンプ
nmap <silent> [ale]<C-P> <Plug>(ale_previous)
nmap <silent> [ale]<C-N> <Plug>(ale_next)'''
# }}}

#airline---{{{
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'

#hook_add---{{{
hook_add = '''
  let g:airline_theme = 'deus'
  set laststatus=2
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#wordcount#enabled = 0
let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'y', 'z']]
let g:airline_section_c = '%t'
let g:airline_section_x = '%{&filetype}'
let g:airline_section_z = '%3l:%2v %{airline#extensions#ale#get_warning()} %{airline#extensions#ale#get_error()}'
let g:airline#extensions#ale#error_symbol = ' '
let g:airline#extensions#ale#warning_symbol = ' '
let g:airline#extensions#default#section_truncate_width = {}
let g:airline#extensions#whitespace#enabled = 1
'''
#}}}
#---}}}
